# Generated by Django 5.0.9 on 2024-10-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zinnia", "0006_alter_entry_options_alter_entry_related"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="entry",
            index_together=set(),
        ),
    ]
